version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: triptally
      POSTGRES_USER: triptally_admin
      POSTGRES_PASSWORD: localpassword
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: ['-jar', 'DynamoDBLocal.jar', '-sharedDb', '-inMemory']
    ports:
      - '8000:8000'

volumes:
  postgres_data:
